# Numpy 101 (a crash course for students)

Just something quick and simple on ***NumPy***. This is of the Python libraries used for ML you need to know something about.

*DISCLAIMER: This material has to be intended as a pragmatic shortcut to move on, and should NOT stop you from attending a more complete course/tutorial*

## Python list vs NumPy array

NumPy provides the foundation data structures and operations for SciPy. These are arrays (_ndarrays_) that are efficient to define and manipulate.

Here is a comparison between a **Python list** (L) and a **NumPy array** (A).

In [1]:
L = [1,2,3]
for i in L:
    print i

1
2
3


In [2]:
import numpy as np

If you have problems in installing a module, see e.g. https://scipy.org/install.html.

In [3]:
A = np.array([1,2,3])

In [4]:
for i in A:
    print i

1
2
3


Looks like they are completely identical! They are not.

Try to do something to your list/array, e.g. append an item.

In [5]:
L.append(4)
L

[1, 2, 3, 4]

In [6]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

This method does not work for arrays because there is no _append_ attribute for a NumPy array. 

Try to join lists.

In [7]:
L = [1,2,3,4]
L = L + [5]
L

[1, 2, 3, 4, 5]

In [8]:
A = np.array([1,2,3])
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

This also does _not_ work on NumPy arrays. 

It seems that NumPy cannot do even the most trivial things that a Pyhton list can do!

Try vector addition now. 

In [9]:
L = [1,2,3,4,5]
L+L     # mmh, is it the right way to go?

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

We can try to add a vector to itself. We are tempted to type as we think, so to use the "+" sign. But in Python lists if we do so we get a new list with all the elements concatenated, and it is not what we want. So we need to add each element individually, after having created a new empty list to host the results.

In [10]:
L = [1,2,3,4,5]
L2 = []
for i in L:
    L2.append(i+i)
L2

[2, 4, 6, 8, 10]

Ok, a bit ugly, but it works.

What about adding a vector to itself in NumPy, then? Let's try using the "+" sign as we wanted to do before with lists.

In [11]:
A = np.array([1,2,3])
A+A

array([2, 4, 6])

Uh, cool! Done!

The "+" sign with Python lists does concatenation, while with NumPy arrays it does element-wise addition, which in this case means addition of two vectors. This concept naturally extends to more dimensions: if you have a N-dim array (i.e. a matrix), doing A+A works. It is still element-wise addition.

Another way to get the same result is via a x2 multiplication, which is a scalar multiplied by a vector.

In [12]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Ops.. let's try with NumPy now.

In [13]:
2*A

array([2, 4, 6])

Done!

With L it concatenates, with A it adds. 

To be clear: you _can_ work with python lists if you want, but if you want to make things work with Python lists, you need to make a loop (as shown above for addition).

Try an element-wise squaring of every element.

In [15]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Ok, not a good way to go. You can do it with a loop:

In [16]:
L2 = []
for i in L:
    L2.append(i*i) # or "i**2"
L2

[1, 4, 9, 16, 25]

OK. But may I guess already that it will be much more manageable and simpler with Numpy arrays? Let's try:

In [17]:
A**2

array([1, 4, 9])

Done!

Other examples?
   * `np.sqrt` does the element-wise square root of the input vector
   * `np.log` does the log
   * `np.exp` the exponential, etc.  

In [18]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [19]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [20]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

<div class="alert alert-block alert-success">
In NumPy, most actions work element-wise. If we want to represent a vector, a NumPy array might be bit more convenient than a Python list as **it does what we expect it to do with NumPy operations**. 
</div>

Lists are useful too, and sometimes you just want those. Usually you can treat a list like an array. With NumPy you can treat an array like a vector, i.e. a mathematical object.

To do operations on lists you need to use a `for` loop, and these are very slow and should be avoided as much as possible for performance reasons.

## Dot product (or "inner product")

It is one important type of multiplication you can perform on vectors, which returns a scalar.

$\mathbf{a} \cdot \mathbf{b} = \mathbf{a}^T\mathbf{b} = \sum_{i=1}^N a_i b_i $

Its outcome (module) is:

$| a \cdot b | = |a||b| cos \theta_{ab} $

i.e. 

$cos \theta_{ab} = \frac {a^T b}{|a||b|}$

The notation with transpose implies that the vectors are by default columns, and the transposition take a vector as column and return the vector as row, then the element-wise multiplication occurs.

## Exercise

<div class="alert alert-block alert-info">
Suppose you have the vectors a and b below. How would you compute the cosine above using numpy? Can you make it with the shortest nb of code lines?
</div>

In [35]:
a = np.array([1,2])
b = np.array([2,1])

## Solution and discussion

Here it is with a for loop..

In [34]:
dot = 0
for i, j in zip(a,b):
    dot += i*j
dot

4

.. and here it is by using NumPy in its full power.

In [24]:
np.sum(a*b)

4

Done! In one line, no visible loops.

Note this:

In [25]:
a*b   # this is the element-wise multiplication, and it returns an array with the single element * element result.

array([2, 2])

One alternative:

In [27]:
(a*b).sum() # it is an instant function so one can call it on the object itself, too

4

Another alternative:

In [28]:
np.dot(a,b)

4

One alternative more:

In [29]:
a.dot(b) # it is an instant function so one can call it on one object and apply to another, too

4

And another (symmetric) one:

In [30]:
b.dot(a) # just because the dot product is commutative

4

So, in one very simple line you compute the dot product between two vectors (and no slow Python loops..).

Now, compute the vector module and $cos \theta_{ab}$.

In [31]:
# the module as sum in quadrature
a_module = np.sqrt(np.sum(a*a))
#a_module = np.sqrt((a*a).sum())   # just equivalent

a_module

2.2360679774997898

Or one can use the `linalg` NumPy module:

In [32]:
a_module = np.linalg.norm(a)
a_module

2.2360679774997898

Combining all together one can find the angle (in radians):


$cos \theta_{ab} = \frac {a^T b}{|a||b|}$

In [ ]:
theta = np.arccos( np.dot(a,b) / ( np.linalg.norm(a) * np.linalg.norm(b) ) )
theta

<div class="alert alert-block alert-success">
This is a one-liner with NumPy, and performant. It would involve lenghty loops with Python lists, and it would be less performant.
</div>

BTW, talking of performances...

## Speed comparison

In [37]:
import numpy as np
from datetime import datetime

a = np.random.randn(100) # 100 random entries, standard normal distribution
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e*f
    return result

t0 = datetime.now()
for t in xrange(T):   # note: this might NOT work in py3 - use range
    slow_dot_product(a, b)
dt_lists = datetime.now() - t0

t0 = datetime.now()
for t in xrange(T):
    np.dot(a,b)
dt_numpy = datetime.now() - t0

t0 = datetime.now()
for t in xrange(T):
    a.dot(b)
dt_numpy2 = datetime.now() - t0

print "With Python list loop: ", dt_lists
print "With NumPy ( np.dot(a,b) ]", dt_numpy
print "With NumPy ( a.dot(b) ]", dt_numpy2

print "dt_numpy / dt_lists:", dt_numpy.total_seconds() / dt_lists.total_seconds()
print "dt_numpy2 / dt_lists:", dt_numpy2.total_seconds() / dt_lists.total_seconds()
print "The numpy method is", 1./(dt_numpy.total_seconds() / dt_lists.total_seconds()), "times faster than the slow method" 
print "The numpy2 method is", 1./(dt_numpy2.total_seconds() / dt_lists.total_seconds()), "times faster than the slow method" 


With Python list loop:  0:00:02.850512
With NumPy ( np.dot(a,b) ] 0:00:00.071954
With NumPy ( a.dot(b) ] 0:00:00.073027
dt_numpy / dt_lists: 0.025242482754
dt_numpy2 / dt_lists: 0.0256189063579
The numpy method is 39.6157545098 times faster than the slow method
The numpy2 method is 39.0336724773 times faster than the slow method


Performance-wise, the `np.dot(a,b)` is >30 times faster. Run it more times to gain statistics and compute an average. Anyway, the conclusion is clear:

<div class="alert alert-block alert-success">
Using a simple dot product calculation as an example, an implementation based on NumPy arrays is >1 order of magnitude faster than a corresponding implementation using Python lists. **Avoid for loops over Python list if you can**.
</div>

This is useful for vectors, i.e. 1D arrays. What about nD arrays?

# Matrices

A matrix can be tought as a 2D array. It can be thought alternatively as a list of lists (indeed, you can use a list of lists to initialize a matrix, for example). Convention: the first index is the row, the second is the column.

A list of lists is as follows:

In [38]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

A matrix in Numpy is as follows:

In [39]:
M = np.array([[1,2], [3,4]])   # NOTE: the 2 lists must be of the same size
M

array([[1, 2],
       [3, 4]])

Or:

In [40]:
M = np.array(L)   # NOTE: the 2 lists must be of the same size
M

array([[1, 2],
       [3, 4]])

_NOTE: the printout seems to indicate already that it is adequate for matrices.._

Let's now see how to get one element of the matrix.

With a Python list of lists:

In [41]:
L[0]   # first element of the list, which is a list itself

[1, 2]

In [42]:
L[0][0]   # first element of the first list of the 2 lists in the list of lists..

1

In [43]:
L[0,0]   # error! and an interesting one!

TypeError: list indices must be integers, not tuple

The same with a NumPy array works - but there is a much better notation, which helps A LOT when one will have to deal with more complicate matrices and related tasks..

In [44]:
M[0][0]

1

In [46]:
M[0,0]   # while L[0,0] did not work (as list indices must be integers, not tuple), this works!

1

Cool! It works exactly with the easy syntax I would like to see working!

Side note: Numpy tends to overkill.. there is already an actual data type for matrices..

In [47]:
M2 = np.matrix([[1,2], [3,4]])
M2

matrix([[1, 2],
        [3, 4]])

NOTE: this builds a matrix, not an array, in NumPy. It is a different data type. It works quite similarly to a NumPy array but it is not exactly the same. Actually the official NumPy documentation suggests _against_ using matrix (!). So we won't care much about this - and eventually you might have easier life in converting matrix datatypes into arrays. After all, converting is easy (see below) and also for arrays you have all convenient matrix operations..

In [48]:
A2 = np.array(M2)
A2

array([[1, 2],
       [3, 4]])

Why is it so cool? See below..

One operation is the Transpose (T).

In [49]:
M3 = np.array([[1,2,3], [3,4,5]])
M3

array([[1, 2, 3],
       [3, 4, 5]])

In [50]:
M3.T

array([[1, 3],
       [2, 4],
       [3, 5]])

Done! `.T` and it works. Wow!

A nxn matrix is just a nD NumPy array. A vector is just a 1D NumPy array (after all, it is a nx1 matrix..). So a 2x2 matrix is just a 2D vector. Actually, it is better to think that **a vector / matrix is a 1D / nD mathematical object that contains numbers**. 

<div class="alert alert-block alert-success">
From a NumPy standpoint, the only thing you should care about is that you are dealing with 1D, 2D, nD NumPy arrays, i.e. treat vectors or matrices regardless.
</div>

## Different ways to generate arrays of data

Type in a list as array content (integers here):

In [51]:
A1 = np.array([1,2,3,4,5])
A1

array([1, 2, 3, 4, 5])

Create an array of all zeros (floating point here):

In [52]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Create a matrix of all zeros (flating point here): easy, just indicate the dimensions.

In [53]:
Z = np.zeros((10,2))
Z

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

NOTE: the input to both definitions above is a tuple containing each dimension.

Equivalent function to create arrays/matrices filled with 1s:

In [54]:
O = np.ones(10)
O

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
O = np.ones((10,2))
O

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Create an array (or a matrix) of random numbers:

In [61]:
R = np.random.random(10)   # uniformily distributed numbers in the [0,1( interval
R
# run this cell several times...

array([ 0.9187636 ,  0.83195816,  0.83646411,  0.10460511,  0.45968634,
        0.33861543,  0.55670617,  0.77728974,  0.11512345,  0.96238782])

In [64]:
G = np.random.randn(10)   # # gaussian distributed numbers with mean 0 and variance 1
G

array([ 0.40216795,  1.69434535, -0.75656561, -0.71389041, -0.28944849,
       -0.52418057, -0.16865848, -1.79111304,  0.07302263,  1.22398005])

NOTE: For `random.randn`, the input need to be integers. This is the only random that takes each dimension as a separate integer, the others take tuples with no problem.

So, this fails:

In [66]:
G = np.random.randn((10,10))   # gaussian distributed numbers with mean 0 and variance 1 - but with a mistake
G

TypeError: an integer is required

Whereas this works:

In [70]:
G = np.random.randn(100,100)   # gaussian distributed numbers with mean 0 and variance 1
G

array([[ 0.08562757,  1.36132334, -1.1208419 , ...,  0.14132817,
        -1.28667876, -0.21109401],
       [-1.12201526, -0.74720984,  1.19138105, ...,  1.0046045 ,
         1.71868058,  1.47638349],
       [-2.12081857,  0.41441157,  1.26768298, ...,  0.16993752,
         1.30406211,  2.74855775],
       ..., 
       [ 0.29412649,  1.31604135, -1.50009618, ...,  0.94556795,
        -0.21654876, -0.06216327],
       [ 0.10422573,  0.4691639 ,  0.02166738, ...,  0.31492853,
         0.02058049,  1.32797174],
       [-0.53432874, -0.09976386,  0.21614445, ..., -1.29540542,
        -0.46315351,  0.3857125 ]])

And we have functions to calculate statistics variables, e.g.:

In [71]:
G.mean()   # mean

-0.0028617690182135827

In [72]:
G.var()   # variance

0.97465251163252364

NOTE: values are pretty close to the true values. 



## Exercise

<div class="alert alert-block alert-info">
Increase the number of random values to more closely match the exact values.
</div>

# Matrix products

In matrix multiplication, inner dimensions must match. If I have a matrix A of size (2,3) and a matrix B of size (3,3), I am allowed to multiply AxB but not BxA. This requirements come from the definition of a dot product:

$ C(i,j) = \sum_{k=1}^N A(i,k) \cdot B(k,j)$

where the $(i,j)$th element of C is the scalar x scalar product between raw $A(i,:)$ and column $B(:,j)$ - with $k$ acting as silent index. In NumPy, this is

    np.dot(A,B)
    
or

    A.dot(B)

Often one wants to multiply matrix elements, i.e. element-wise multiplication.

$C(i,j) = A(i,j) * B(i,j)$

We saw that this "asterisk" operator works for vectors, we want the same for matrices, in nD - i.e. we want this to work also for nD NumPy arrays. Both multidimentional arrays must be of the exact same size, though. 

<div class="alert alert-block alert-success">
In NumPy, the "asterisk" $C(i,j) = A(i,j) * B(i,j)$) means element-by-element (element-wise) multiplication while the "dot" ($C(i,j) = \sum_{k=1}^N A(i,k) \cdot B(k,j)$) means dot product, or **inner product**, i.e. matrix multiplication.
</div>

## Other common matrix operations

Create a matrix to use.

In [75]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

## Matrix inverse

(plus check it is ok):

In [76]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [77]:
np.dot(A,Ainv)   # check that their dot product is the identity matrix - equivalent to A.dot(Ainv) or Ainv.dot(A)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

## Matrix determinant

In [78]:
np.linalg.det(A)

-2.0000000000000004

## Diagonal of a matrix

In [79]:
np.diag(A)   # it return the diagonal in a vector

array([1, 4])

A matrix of all zeros apart from a given diagonal which is a vector you have:

In [80]:
diag = [1,2]
np.diag(diag)

array([[1, 0],
       [0, 2]])

## Outer product (+ review of previously introduced product types)

Outer product comes up when e.g. you calculate the covariance of some sample vector.

$E \{(x-\bar{x})(x-\bar{x})^T\} \approx \frac{1}{N-1} \sum_{i=1}^{N} (x_{i}-\bar{x})(x_{i}-\bar{x})$

Let's review all we saw, plus add the aforementioned product.

In [81]:
a = np.array([1,2])
b = np.array([3,4])

Element-wise product: $C(i,j) = A(i,j) * B(i,j)$

In [82]:
a*b

array([3, 8])

Inner (dot) product: $C(i,j) = \sum_{k=1}^N A(i,k) \cdot B(k,j)$

In [83]:
np.dot(a,b)

11

Outer product: $C(i,j) = A(i) B(j)$ (so that Inner product is the sum product over $i$ in $A(i)B(i)$)

In [84]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

Note that its diagonal is the element-wise product:

In [86]:
np.diag(np.outer(a,b))

array([3, 8])

And the trace gives the inner product:

In [87]:
np.trace(np.outer(a,b))

11

In case of explorations of nD operations, with n>1, take note of the following:

**numpy.dot**: for 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b.<br>

**numpy.inner**: ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

## Back to the start

Re-do few thing to solidify concepts.

Here is how easily one converts a **Python list** into a **NumPy array**.

In [94]:
import numpy   # NOTE: I am deliberately NOT adding "as np" so you familiarize seeing this too..

In [96]:
mylist = [1, 2, 3]                    # Python list
myarray = numpy.array(mylist)         # NumPy array

print(mylist)
print(myarray)
print(myarray.shape)                  # nb rows and columns
print(myarray[0])

[1, 2, 3]
[1 2 3]
(3,)
1


Array notation and ranges can be used to efficiently access data in a NumPy array

In [97]:
# access values
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)

print(myarray)
print(myarray.ndim)
print(myarray.size)
print(myarray.shape)
print(myarray.dtype)


print("\nFirst row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])
print("Specific row and col: %s" % myarray[0, 2])        # myarray[row, column]
print("Whole col: %s" % myarray[:, 2])

[[1 2 3]
 [3 4 5]]
2
6
(2, 3)
int64

First row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 3
Whole col: [3 5]


In [98]:
import numpy as np
myarray = np.arange(4)

print myarray

[0 1 2 3]


In [99]:
myarray = np.arange(1,25)

print myarray

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [100]:
myarray = np.arange(1,25).reshape(2,3,4)

print myarray

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [101]:
myarray = np.arange(6).reshape(1,3,2)

print myarray

[[[0 1]
  [2 3]
  [4 5]]]


NumPy arrays can be used directly in arithmetic.

In [102]:
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])

print("Addition: %s" % (myarray1 + myarray2))
print("Multiplication: %s" % (myarray1 * myarray2))

Addition: [5 5 5]
Multiplication: [6 6 6]


In [103]:
myarray = np.arange(9).reshape(3,3)
print myarray
myarray+myarray

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [104]:
myarray*myarray

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [105]:
myarray+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
myarray*4+1

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33]])

Broadcasting

In [107]:
myarray2 = np.array([10,10,10])

print myarray
print myarray2
print myarray+myarray2

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10 10 10]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


There is a lot more to NumPy arrays but these examples give you a flavor of the efficiency they provide when you would happen to work with lots of numerical data. 

## Done. That's all for the NumPy 101 crash course.

The appetizer is over. Time for you to move to the main course, i.e. a good NumPy course and/or tutorial.

## What we have learnt

Basics of Numpy.

Understanding the effective use of NumPy arrays is fundamental to effective numerical computing in Python.

## Reading material

* SciPy Lecture Notes, http://www.scipy-lectures.org/
* NumPy User Guide, http://docs.scipy.org/doc/numpy/user/